name: unimacro
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_13
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gcc_impl_linux-64=9.5.0=h99780fb_19
  - gcc_linux-64=9.5.0=h4258300_13
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gxx_impl_linux-64=9.5.0=h99780fb_19
  - gxx_linux-64=9.5.0=h43f449f_13
  - idna=3.7=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=9.5.0=h0a57e50_19
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libsanitizer=9.5.0=h2f262e1_19
  - libstdcxx-devel_linux-64=9.5.0=h0a57e50_19
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.10=py39h5eee18b_0
  - mkl_random=1.2.7=py39h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - numpy=2.0.1=py39h5f9d8c6_1
  - numpy-base=2.0.1=py39hb5e798b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pillow=10.4.0=py39h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.20=he870216_1
  - pytorch=2.5.0=py3.9_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py39h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py39h06a4308_0
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.14.0=pyh04b8f61_5
  - sysroot_linux-64=2.12=he073ed8_17
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.5.0=py39_cu121
  - torchtriton=3.1.0=py39
  - torchvision=0.20.0=py39_cu121
  - typing_extensions=4.11.0=py39h06a4308_0
  - urllib3=2.2.3=py39h06a4308_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.60.2
      - importlib-resources==6.5.2
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - lmdb==1.5.1
      - matplotlib==3.9.4
      - msgpack==1.1.0
      - packaging==25.0
      - pandas==2.3.3
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rdkit==2022.9.5
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.17.0
      - threadpoolctl==3.6.0
      - tqdm==4.66.5
      - tzdata==2025.3
      - zipp==3.23.0
prefix: /share/home/202320162823/anaconda3/envs/unimacro
